# options for analysis running
run:
  deadline: 2m
  build-tags:
    - integration

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
          -
  golint:
    min-confidence: 0.8

  goimports:
    local-prefixes: x-qdo/jiraclick

  gocyclo:
    min-complexity: 10

  maligned:
    suggest-new: true

  dupl:
    threshold: 165

  goconst:
    min-occurrences: 2

  misspell:
    locale: US
    ignore-words:
      - pprof

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  enable-all: false
  disable-all: true
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - lll

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - golint
      text: "returns unexported type"

  max-issues-per-linter: 0
  max-same-issues: 0
