debug: true
rabbitmq:
  host: 127.0.0.1
  port: 5672
  user: user
  password: pass
  vhost:
httphandler:
  port: 8080
metrics:
  port: 9090
clickup:
  webhooksecret: ""
  token: "pk_"
  list: "10942379"
  host: "https://api.clickup.com/api/v2"
jira:
  CQYUVTWH2:
    username: ""
    apitoken: ""
    baseurl: "https://iiziservices.atlassian.net"
    project: "DOPS"
  CQTG74FUH:
    username: ""
    apitoken: ""
    baseurl: "https://iiziservices.atlassian.net"
    project: "DOPS"
