debug: true
rabbitmq:
  host: 127.0.0.1
  port: 5672
  user: user
  password: pass
  vhost:
http:
  port: 8080
metrics:
  port: 9090
clickup:
  host: "https://api.clickup.com/api/v2"
  token: "pk_"
  list_id: "123"
