apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jiraclick.fullname" . }}-api
  labels:
    {{- include "jiraclick.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jiraclick.selectorLabels" . | nindent 6 }}
      role: api
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
      labels:
        {{- include "jiraclick.selectorLabels" . | nindent 8 }}
        role: api
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jiraclick.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: webhooks
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/app" ]
          args:
            - http-handler
          env:
            {{ include "jiraclick.common_env" . | nindent 12 }}
            - name: HTTPHANDLER_PORT
              value: "8080"
            - name: METRICS_PORT
              value: "9090"
          envFrom:
            - configMapRef:
                name: opentelemetry-config
          ports:
            - name: http-handler
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http-handler
          readinessProbe:
            httpGet:
              path: /health-check
              port: http-handler
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
