apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jiraclick.fullname" . }}
  labels: {{- include "jiraclick.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.clickup }}
  clickup_{{$key}}_webhooksecret: {{$value.webhooksecret | b64enc | quote}}
  clickup_{{$key}}_token: {{$value.token | b64enc | quote}}
  {{- end }}
  {{- range $key, $value := .Values.jira }}
  jira_{{$key}}_username: {{$value.username | b64enc | quote}}
  jira_{{$key}}_apitoken: {{$value.apitoken | b64enc | quote}}
  {{- end }}
  rabbitmq_url: {{.Values.rabbitmq.url | b64enc | quote}}
  config_content: {{.Values.config_content | b64enc | quote}}
