apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jiraclick.fullname" . }}
  labels: {{- include "jiraclick.labels" . | nindent 4 }}
data:
  clickup_token: {{.Values.clickup.token | b64enc | quote}}
  clickup_webhooksecret: {{.Values.clickup.webhooksecret | b64enc | quote}}
  jira_GQCCU8SCW_apitoken: {{.Values.jira.GQCCU8SCW.apitoken | b64enc | quote}}
  rabbitmq_url: {{.Values.rabbitmq.url | b64enc | quote}}
