apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jiraclick.fullname" . }}
  labels: {{- include "jiraclick.labels" . | nindent 4 }}
data:
  clickup_token: {{.Values.clickup.token | b64enc | quote}}
  clickup_webhooksecret: {{.Values.clickup.webhooksecret | b64enc | quote}}
  jira_CQYUVTWH2_username: {{.Values.jira.CQYUVTWH2.username | b64enc | quote}}
  jira_CQYUVTWH2_apitoken: {{.Values.jira.CQYUVTWH2.apitoken | b64enc | quote}}
  jira_CQTG74FUH_username: {{.Values.jira.CQTG74FUH.username | b64enc | quote}}
  jira_CQTG74FUH_apitoken: {{.Values.jira.CQTG74FUH.apitoken | b64enc | quote}}
  rabbitmq_url: {{.Values.rabbitmq.url | b64enc | quote}}
