{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jiraclick.serviceAccountName" . }}
  labels:
{{ include "jiraclick.labels" . | nindent 4 }}
{{- end -}}
